<?php
/** @var \MageOS\Widgetkit\Block\Widgets\GridStacked $this */
$titleType = \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_grid_stacked_title_type'));
$titleCssClasses = $this->getData('mageos_grid_stacked_title_classes');
$descriptionCssClasses = $this->getData('mageos_grid_stacked_description_classes');
?>
<?= $this->getChildHtml("previewAssets"); ?>
<?php if (!empty($this->getData('mageos_grid_stacked_title'))): ?>
<<?= $titleType ?> class="<?= $escaper->escapeHtmlAttr($titleCssClasses ?? ''); ?>">
    <?= $escaper->escapeHtml(\MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_grid_stacked_title'))); ?>
</<?= \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_grid_stacked_title_type')); ?>>
<?php endif; ?>

<?php if (!empty($this->getData('mageos_grid_stacked_description'))): ?>
<div class="<?= $escaper->escapeHtmlAttr($descriptionCssClasses ?? ''); ?>">
    <?= \MageOS\Widgetkit\Model\RichTextDecoder::html($this->getData('mageos_grid_stacked_description')); ?>
</div>
<?php endif; ?>

<?php $this->setMainTemplate('MageOS_Widgetkit::widget/hyva/grid-stacked/template-v1.phtml'); ?>
<?= $this->renderMainTemplate(); ?>
