<?php
/** @var \MageOS\Widgetkit\Block\Widgets\GridStacked $this */
$titleType = $this->getData('mageos_grid_stacked_title_type');
$titleCssClasses = $this->getData('mageos_grid_stacked_title_classes');
$descriptionCssClasses = $this->getData('mageos_grid_stacked_description_classes');
?>
<?= $this->getChildHtml("previewAssets"); ?>
<?php if (!empty($this->getData('mageos_grid_stacked_title'))): ?>
<<?= $titleType ?> class="<?= $titleCssClasses; ?>">
    <?= /* @noEscape */ \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_grid_stacked_title')); ?>
</<?= $this->getData('mageos_grid_stacked_title_type'); ?>>
<?php endif; ?>

<?php if (!empty($this->getData('mageos_grid_stacked_description'))): ?>
<div class="<?= $descriptionCssClasses; ?>">
    <?= \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_grid_stacked_description')); ?>
</div>
<?php endif; ?>

<?php $this->setMainTemplate('MageOS_Widgetkit::widget/hyva/grid-stacked/template-v1.phtml'); ?>
<?= $this->renderMainTemplate(); ?>
