<?php
/**
 * Render slideshow component for Hyvä theme
 */
$titleType = $this->getData('mageos_slideshow_title_type');
$titleCssClasses = $this->getData('mageos_slideshow_title_classes');
$descriptionCssClasses = $this->getData('mageos_slideshow_description_classes');
?>
<?= $this->getChildHtml("previewAssets"); ?>
<?php if (!empty($this->getData('mageos_slideshow_title'))): ?>
<<?= $titleType ?> class="<?= $titleCssClasses; ?>">
    <?= /* @noEscape */ \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_slideshow_title')); ?>
</<?= $this->getData('mageos_slideshow_title_type'); ?>>
<?php endif; ?>

<?php if (!empty($this->getData('mageos_slideshow_description'))): ?>
<div class="<?= $descriptionCssClasses; ?>">
    <?= \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_slideshow_description')); ?>
</div>
<?php endif; ?>

<?= $this->renderMainTemplate(); ?>
