<?php
/**
 * Render slider component for Hyvä theme
 */
$titleType = \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_slider_title_type'));
$titleCssClasses = $this->getData('mageos_slider_title_classes');
$descriptionCssClasses = $this->getData('mageos_slider_description_classes');
?>
<?= $this->getChildHtml("previewAssets"); ?>
<?php if (!empty($this->getData('mageos_slider_title'))): ?>
<<?= $titleType ?> class="<?= $escaper->escapeHtmlAttr($titleCssClasses ?? ''); ?>">
    <?= $escaper->escapeHtml(\MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_slider_title'))); ?>
</<?= \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_slider_title_type')); ?>>
<?php endif; ?>

<?php if (!empty($this->getData('mageos_slider_description'))): ?>
<div class="<?= $escaper->escapeHtmlAttr($descriptionCssClasses ?? ''); ?>">
    <?= \MageOS\Widgetkit\Model\RichTextDecoder::html($this->getData('mageos_slider_description')); ?>
</div>
<?php endif; ?>

<?= $this->renderMainTemplate(); ?>
