<?php
use Magento\Backend\Block\Page\RequireJs;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var RequireJs $block */
/** @var SecureHtmlRenderer $secureRenderer */

$escaper = $escaper ?? $block;
$alpineJsPath = $block->getData('alpinejs_path');
?>
<?php if ($alpineJsPath): ?>
   <script src="<?php echo $block->getViewFileUrl($alpineJsPath); ?>"></script>
<?php endif; ?>

<?php
$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->getUrl('*') . '\';
    var FORM_KEY = \'' . /* @noEscape */ $block->getFormKey() . '\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->getViewFileUrl('/') . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
?>
