<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\Widgetkit\Block\Adminhtml\GridStacked\Preview;
use Magento\Framework\Escaper;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var Preview $block
 * @var Escaper $escaper
 */
$uniqId = uniqid();
$titleCssClasses = $this->getData('mageos_grid_stacked_title_classes');
$descriptionCssClasses = $this->getData('mageos_grid_stacked_description_classes');
?>
<div class="grid-stacked-widget">
    <?= $this->getChildHtml("previewAssets"); ?>
    <?php if (!empty($this->getData('mageos_grid_stacked_title'))): ?>
        <<?= $this->getData('mageos_grid_stacked_title_type'); ?> class="<?= $titleCssClasses; ?>">
            <?= /* @noEscape */ \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_grid_stacked_title')); ?>
        </<?= $this->getData('mageos_grid_stacked_title_type'); ?>>
    <?php endif; ?>
    <?php if (!empty($this->getData('mageos_grid_stacked_description'))): ?>
        <div class="<?= $descriptionCssClasses; ?>"><?= \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_grid_stacked_description')); ?></div>
    <?php endif; ?>

    <?php $this->setMainTemplate('MageOS_Widgetkit::widget/hyva/grid-stacked/template-v1.phtml'); ?>
    <div id="widget<?= $uniqId; ?>">
        <?= $this->renderMainTemplate(); ?>
    </div>
</div>
