<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\Widgetkit\Block\Adminhtml\Marquee\Preview;
use Magento\Framework\Escaper;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var Preview $block
 * @var Escaper $escaper
 */
$uniqId = uniqid();
$titleCssClasses = $this->getData('mageos_marquee_title_classes');
$descriptionCssClasses = $this->getData('mageos_marquee_description_classes');
?>
<div class="marquee-widget">
    <?= $this->getChildHtml("previewAssets"); ?>
    <?php if (!empty($this->getData('mageos_marquee_title'))): ?>
        <<?= $this->getData('mageos_marquee_title_type'); ?> class="<?= $titleCssClasses; ?>">
            <?= /* @noEscape */ \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_marquee_title')); ?>
        </<?= $this->getData('mageos_marquee_title_type'); ?>>
    <?php endif; ?>
    <?php if (!empty($this->getData('mageos_marquee_description'))): ?>
        <div class="<?= $descriptionCssClasses; ?>"><?= \MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_marquee_description')); ?></div>
    <?php endif; ?>

    <div id="widget<?= $uniqId; ?>">
        <?= $this->renderMainTemplate(); ?>
    </div>
</div>
