<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\Widgetkit\Block\Adminhtml\ProductSlider\Preview;
use Magento\Framework\Escaper;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var Preview $block
 * @var Escaper $escaper
 *
 * PageBuilder stage preview for the "Full" carousel template variant.
 */
$uniqId = uniqid();
$titleCssClasses = $this->getData('mageos_product_slider_title_classes');
$descriptionCssClasses = $this->getData('mageos_product_slider_description_classes');
?>
<div class="product-slider-widget">
    <?= $this->getChildHtml("previewAssets"); ?>
    <?php if (!empty($this->getData('mageos_product_slider_title'))): ?>
        <<?= \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_product_slider_title_type')); ?> class="<?= $escaper->escapeHtmlAttr($titleCssClasses ?? ''); ?>">
            <?= $escaper->escapeHtml(\MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_product_slider_title'))); ?>
        </<?= \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_product_slider_title_type')); ?>>
    <?php endif; ?>
    <?php if (!empty($this->getData('mageos_product_slider_description'))): ?>
        <div class="<?= $escaper->escapeHtmlAttr($descriptionCssClasses ?? ''); ?>"><?= \MageOS\Widgetkit\Model\RichTextDecoder::html($this->getData('mageos_product_slider_description')); ?></div>
    <?php endif; ?>

    <div id="widget<?= $uniqId; ?>">
        <?php $this->setMainTemplate('MageOS_Widgetkit::widget/hyva/product-slider/template-full.phtml'); ?>
        <?= $this->renderMainTemplate(); ?>
    </div>
</div>
