<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\Widgetkit\Block\Adminhtml\Tab\Preview;
use Magento\Framework\Escaper;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var Preview $block
 * @var Escaper $escaper
 */
$uniqId = uniqid();
$titleCssClasses = $this->getData('mageos_tab_title_classes');
$descriptionCssClasses = $this->getData('mageos_tab_description_classes');
?>
<div class="tab-widget">
    <?= $this->getChildHtml("previewAssets"); ?>
    <?php if (!empty($this->getData('mageos_tab_title'))): ?>
        <<?= \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_tab_title_type')); ?> class="<?= $escaper->escapeHtmlAttr($titleCssClasses ?? ''); ?>">
            <?= $escaper->escapeHtml(\MageOS\Widgetkit\Model\RichTextDecoder::decode($this->getData('mageos_tab_title'))); ?>
        </<?= \MageOS\Widgetkit\Model\WidgetOutput::heading($this->getData('mageos_tab_title_type')); ?>>
    <?php endif; ?>
    <?php if (!empty($this->getData('mageos_tab_description'))): ?>
        <div class="<?= $escaper->escapeHtmlAttr($descriptionCssClasses ?? ''); ?>"><?= \MageOS\Widgetkit\Model\RichTextDecoder::html($this->getData('mageos_tab_description')); ?></div>
    <?php endif; ?>

    <div id="widget<?= $uniqId; ?>">
        <?= $this->renderMainTemplate(); ?>
    </div>
</div>
